// Common enums for GastroFlow Protocol Buffers
// This file will contain generated TypeScript enum definitions

export enum PackingMode {
  PACKING_MODE_UNSPECIFIED = 0,
  PACKING_MODE_HERE = 1,
  PACKING_MODE_TAKEAWAY = 2,
  PACKING_MODE_DELIVERY = 3,
  PACKING_MODE_YAEAT = 4,
}

export enum PaymentMethod {
  PAYMENT_METHOD_UNSPECIFIED = 0,
  PAYMENT_METHOD_CARD = 1,
  PAYMENT_METHOD_CASH = 2,
  PAYMENT_METHOD_TRANSFER = 3,
  PAYMENT_METHOD_DEPOSIT = 4,
  PAYMENT_METHOD_LATER = 5,
}

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  ORDER_STATUS_DRAFT = 1,
  ORDER_STATUS_PENDING = 2,
  ORDER_STATUS_CONFIRMED = 3,
  ORDER_STATUS_PREPARING = 4,
  ORDER_STATUS_READY = 5,
  ORDER_STATUS_IN_DELIVERY = 6,
  ORDER_STATUS_COMPLETED = 7,
  ORDER_STATUS_CANCELLED = 8,
  ORDER_STATUS_REFUNDED = 9,
}

export enum UserRole {
  USER_ROLE_UNSPECIFIED = 0,
  USER_ROLE_CUSTOMER = 1,
  USER_ROLE_STAFF = 2,
  USER_ROLE_MANAGER = 3,
  USER_ROLE_ADMIN = 4,
  USER_ROLE_OWNER = 5,
}

export enum MenuItemStatus {
  MENU_ITEM_STATUS_UNSPECIFIED = 0,
  MENU_ITEM_STATUS_AVAILABLE = 1,
  MENU_ITEM_STATUS_UNAVAILABLE = 2,
  MENU_ITEM_STATUS_OUT_OF_STOCK = 3,
  MENU_ITEM_STATUS_SEASONAL = 4,
}

export enum RestaurantStatus {
  RESTAURANT_STATUS_UNSPECIFIED = 0,
  RESTAURANT_STATUS_OPEN = 1,
  RESTAURANT_STATUS_CLOSED = 2,
  RESTAURANT_STATUS_BUSY = 3,
  RESTAURANT_STATUS_MAINTENANCE = 4,
}

export enum Language {
  LANGUAGE_UNSPECIFIED = 0,
  LANGUAGE_RU = 1,
  LANGUAGE_EN = 2,
  LANGUAGE_KK = 3,
}